---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: map-maker
  namespace: rhtap-o11y--runtime-int
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: map-maker
subjects:
  - kind: ServiceAccount
    name: map-maker
    namespace: rhtap-o11y--runtime-int
