---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ws-map-maker
spec:
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - ws-map-maker-job.sh
              env:
                - name: KUBECONFIG
                  value: ""
                - name: KUBECONFIG_SRC
                  value: /usr/local/etc/kube-config/kube-config
                - name: CONTEXTS
                  value: rh01 m01
              image: >-
                image-registry.openshift-image-registry.svc:5000/
                rhtap-o11y--runtime-int/segment-bridge-job
              imagePullPolicy: Always
              name: ws-map-maker
              tty: true
              volumeMounts:
                - mountPath: /usr/local/etc/kube-config
                  name: kube-config
                  readOnly: true
          restartPolicy: Never
          serviceAccount: map-maker
          volumes:
            - name: kube-config
              secret:
                secretName: kube-config
  schedule: "@hourly"
  successfulJobsHistoryLimit: 3
