---
name: container Unit tests
"on":
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
      - name: test kwok
        run: go test -short -v ./kwok/...
      - name: test splunk
        run: go test -short -v ./splunk/...
