---
name: gitlint checks on Pull Request
"on":
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  gitlint:
    name: Run gitlint checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install Python dependencies
        run: pip install -r requirements.lock
      - name: Run gitlint on CI with pre-commit
        run: >-
          gitlint --commits origin/${{ github.event.pull_request.base.ref
          }}..HEAD
