---
name: Pre-commit
"on":
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Python dependencies
        run: pip install -r requirements.lock
      - name: Run pre-commit
        run: pre-commit run --all-files
      - name: Run gitlint on the latest commit message
        run: >-
          pre-commit run gitlint --hook-stage commit-msg --commit-msg-filename
          .git/COMMIT_EDITMSG
